### PR TITLE
Resampling fix

### LINKED ISSUE #57: Nightly builds failing for a few months
**What happened**:

Dear authors and/or contributors (cc'ing @jukent @anissa111  and @kafitzgerald), the nightly builds of this cookbook have been failing for the last few months. 

Could you please have a look at it?

**Minimal Complete Verifiable Example**:

[Latest nightly build](https://github.com/ProjectPythia/advanced-viz-cookbook/actions/runs/11378416921/job/31654159314) as of the creation of this issue.

**Anything else we need to know?**:

If you think it is due to Pythia infrastructure or something else other than the cookbook itself, please let us know.

### PR DESCRIPTION
**Pull request by kafitzgerald**
Adapts the resampling code to address upstream changes in Xarray and the animation notebook to work with Xarray and NumPy >= 2.0.

Closes #57

### CODE REVIEW

**Comment by kafitzgerald** [comment]
The build failure here is unrelated to the fix, but rather something else that's broken.

It looks like it's an issue in the animation notebook.  Trying to pin down the issue, but I think it might be some other recent Xarray changes.

**Comment by kafitzgerald** [comment]
Or rather Xarray interactions w/ NumPy 2.0.2 (may just be Numpy 2+)

**Comment by kafitzgerald** [comment]
Looks like it's this https://github.com/pydata/xarray/issues/9043

We're passing DataArrays to np.linspace (buried in the Xarray code) via the vmin and vmax params.

**Comment by kafitzgerald** [comment]
@jukent, I think I may have broken the automatic reviewer assignment or maybe it doesn't work for cookbooks.  Either way, it doesn't look like folks are getting assigned automatically and I don't have permissions to request a review.  

This should address the CI failures though.

**Review by jukent — APPROVED** [review]
Thanks for looking into this @kafitzgerald 

I don't believe we have automatic reviews for Cookbooks since there is usually a smaller "team" associated with the dev for each one.

**Comment by kafitzgerald** [comment]
@jukent ah, I see.  I saw something in the PR template about it, but I'm guessing that propagated from some Project Pythia templating.  

Feel free to merge.  I don't have permissions on this.  

And if you'd rather not squash-merge, I can clean up the commit history.  Just let me know.

**Pull request merged**
