### PR TITLE
Get the "Interactive Plots" to work and show up

### PR DESCRIPTION
**Pull request by erogluorhan**
This PR mainly uses the mpas-datashader.ipynb, making some changes in it to cover interactive plotting in this cookbook and emphasize there were some updates in unstructured grids visualization via UXarray since the initial version of this study was conducted.

This PR does:
- Rename "mpas-datashader.ipynb" to "interactive-holoviz-mpas"
- Revise the text to handle updated information on unstructured grids/interactive visualization
- Add an "important" admonition into the beginning of the notebook about UXarray cookbook (Link to it is currently 404 but will hopefully work after that cookbook is published)
- Add tips to encourage interactivity with the plots
- Swap the order of "Interactive plots" and "Animation" in the cookbook, i.e. the former is the final chapter now in the cookbook

### CODE REVIEW

**Comment by jukent** [comment]
Thanks for fixing the toc!

**Comment by anissa111** [comment]
Should this section go after animation instead of before? If not, the spaghetti plots notebook should point to this notebook in the "whats next" section I think

**Comment by jukent** [comment]
Yes the "what's next" sections will need to be corrected. I agree we could put this after animation.

**Comment by philipc2** [comment]
While the flow and content of this notebook is good, I think it misses the point of being used to showcase the interactive functionality of HoloViews.
* Dynamic rasterization (i.e. `dynamic=True`) is only mentioned in the admonition, however this is one of the most important parameters for interactive visualization at high-resolution ([my discussion from the UXarray cookbook](https://uxarray.github.io/unstructured-grid-viz-cookbook/notebooks/03-uxarray-vis/06-performance.html#polygon-vs-point-rasters))
* No mention to panels, additional hover tools, HoloMaps, or other HoloViz interactive functionality (there is a lot more to interactive plotting than just panning, unless that is the aim of this notebook), a few examples
  * https://holoviews.org/gallery/apps/bokeh/mandelbrot.html
  * https://holoviews.org/reference/apps/bokeh/player.html
  * https://holoviews.org/reference/containers/bokeh/HoloMap.html
* Personally, it still feels like too much of the content of this notebook is dedicated to "Unstructured Grid Visualization", with the only "interactive" elements of this notebook being the outputted plots. There is also no "interactive" difference between the three rendered plots

A think there should be a much greater emphasis put into explaining the actual interactivity of these plots. A few suggestions
* Reduce the amount of non-interactive visualization. At the minimum, I'd exclude the "Synthesizing triangles from points using Delaunay triangulation" section
* There is still too many comments in each code cell
* Can you provide an example to where setting `dynamic` to True or False makes a difference
* Describe what the `.opts` accessor is doing, what is the point of doing `tools=['hover']`

What do you think?

**Comment by erogluorhan** [comment]
> Should this section go after animation instead of before? If not, the spaghetti plots notebook should point to this notebook in the "whats next" section I think

> Yes the "what's next" sections will need to be corrected. I agree we could put this after animation.

Yes, I have addressed these both

**Comment by philipc2** [comment]
> > While the flow and content of this notebook is good, I think it misses the point of being used to showcase the interactive functionality of HoloViews.
> > 
> > * Dynamic rasterization (i.e. `dynamic=True`) is only mentioned in the admonition, however this is one of the most important parameters for interactive visualization at high-resolution ([my discussion from the UXarray cookbook](https://uxarray.github.io/unstructured-grid-viz-cookbook/notebooks/03-uxarray-vis/06-performance.html#polygon-vs-point-rasters))
> > * No mention to panels, additional hover tools, HoloMaps, or other HoloViz interactive functionality (there is a lot more to interactive plotting than just panning, unless that is the aim of this notebook), a few examples
> >   
> >   * https://holoviews.org/gallery/apps/bokeh/mandelbrot.html
> >   * https://holoviews.org/reference/apps/bokeh/player.html
> >   * https://holoviews.org/reference/containers/bokeh/HoloMap.html
> > * Personally, it still feels like too much of the content of this notebook is dedicated to "Unstructured Grid Visualization", with the only "interactive" elements of this notebook being the outputted plots. There is also no "interactive" difference between the three rendered plots
> > 
> > A think there should be a much greater emphasis put into explaining the actual interactivity of these plots. A few suggestions
> > 
> > * Reduce the amount of non-interactive visualization. At the minimum, I'd exclude the "Synthesizing triangles from points using Delaunay triangulation" section
> > * There is still too many comments in each code cell
> > * Can you provide an example to where setting `dynamic` to True or False makes a difference
> > * Describe what the `.opts` accessor is doing, what is the point of doing `tools=['hover']`
> > 
> > What do you think?
> 
> These reviews are invaluable! I agree with all of them and will be working on getting them addressed.

Fantastic! One suggestion to keep in mind

For the sections of the notebook, what do you think of having it broken down into the following Sub Titles

--- 

# HoloViz
## Overview

Content here would be mostly unchanged 

## Trimesh Visualization

Content would almost be mostly unchanged, however slightly condensed, as per the points I gave above. 

## Interactivity 
New content to this notebook, would manipulate the plots from the `Trimesh Visualuzation` section to showcase the interactive features of HoloViews.

**Comment by erogluorhan** [comment]
> While the flow and content of this notebook is good, I think it misses the point of being used to showcase the interactive functionality of HoloViews.

It now emphasizes interactivity more (even though I kept the primal and dual mesh parts for not only getting the data ready for visualization but also keeping them as reference for the future. However, I now name those parts as "preprocessing" that suggests it's not direclt visualization-related)

> * Dynamic rasterization (i.e. `dynamic=True`) is only mentioned in the admonition, however this is one of the most important parameters for interactive visualization at high-resolution ([my discussion from the UXarray cookbook](https://uxarray.github.io/unstructured-grid-viz-cookbook/notebooks/03-uxarray-vis/06-performance.html#polygon-vs-point-rasters))

We now have a separate part dedicated to its discussion

> * No mention to panels, additional hover tools, HoloMaps, or other HoloViz interactive functionality (there is a lot more to interactive plotting than just panning, unless that is the aim of this notebook), a few examples
   
>   * https://holoviews.org/gallery/apps/bokeh/mandelbrot.html
>   * https://holoviews.org/reference/apps/bokeh/player.html
>   * https://holoviews.org/reference/containers/bokeh/HoloMap.html

These are great recommendations, though I thought discussing mandelbrot, panel, HoloMap could expand the scope too much, so I included them as "further reading" recommendations in the text.

> * Personally, it still feels like too much of the content of this notebook is dedicated to "Unstructured Grid Visualization", with the only "interactive" elements of this notebook being the outputted plots. There is also no "interactive" difference between the three rendered plots

Thanks very much for this; it was much helpful for me to rethink about the flow and content. Now, interactivity has a whole section of it under which several subjects are discussed. Though, I still would like to keep primal and dual mesh parts as "preprocessing" because of the reasons mentioned in the beginning of this comment

> A think there should be a much greater emphasis put into explaining the actual interactivity of these plots. A few suggestions
> 
> * Reduce the amount of non-interactive visualization. At the minimum, I'd exclude the "Synthesizing triangles from points using Delaunay triangulation" section

Done; thanks a lot!

> * There is still too many comments in each code cell

Instead of removing the code cell comments, I had added the following admonition to explain for what purpose comments in the code cells would work:

image

What do you think?

> * Can you provide an example to where setting `dynamic` to True or False makes a difference

Added the "Dynamic plot" section to discuss this.

> * Describe what the `.opts` accessor is doing, what is the point of doing `tools=['hover']`

Added the "Holoviews’ options system: opts" section to discuss this.

**Comment by jukent** [comment]
Couple minor notes:

- add yourself (and John? Philip?) as an author in the README and CITATION.cff
- in the first admonition "we highly recommend to see also" should be changed to something like "we highly recommend checking out" or "we highly recommend looking at" for grammar

will add more notes after lunch!

**Comment by erogluorhan** [comment]
> Couple minor notes:
> 
> * add yourself (and John? Philip?) as an author in the README and CITATION.cff
> * in the first admonition "we highly recommend to see also" should be changed to something like "we highly recommend checking out" or "we highly recommend looking at" for grammar
> 
> will add more notes after lunch!

Great catches; thanks! Addressed these all and once the build succeeds, you can give it another look

**Comment by erogluorhan** [comment]
> I've compiled some comments here, let me know if you can access it 
> https://app.reviewnb.com/philipc2/advanced-viz-cookbook/blob/interactive_plots/notebooks%2Finteractive-holoviz-mpas.ipynb

Yeah, thanks! I have addressed them all, and they were great to improve things significantly.

> * Check for grammar throughout

I believe it is completed now.

> * Please run the `pre-commit` on the notebook to fix the formatting of some of the cells, and generally try to keep code comments to a minimal (use docstrings for function descriptions, move descriptive code into markdown cells, etc.)

Actually pre-commit gets angry with several other notebooks too, so @jukent may hav a better understanding on what is going on there.

**Review by philipc2 — CHANGES_REQUESTED** [review]
Looking good! 

Only thing that appears to be missing is a note/warning regarding the "dynamic" option not actually being dynamic in the rendered notebook.

**Comment by erogluorhan** [comment]
> Looking good!
> 
> Only thing that appears to be missing is a note/warning regarding the "dynamic" option not actually being dynamic in the rendered notebook.

Ok, I can do that, but instead of that, do you think it'd be worth making all the prior plots with `dynamic=False` and just start doing them True dynamic here so that the plot would comply with the title better?

**Comment by philipc2** [comment]
> > Looking good!
> > Only thing that appears to be missing is a note/warning regarding the "dynamic" option not actually being dynamic in the rendered notebook.
> 
> Ok, I can do that, but instead of that, do you think it'd be worth making all the prior plots with `dynamic=False` and just start doing them True dynamic here so that the plot would comply with the title better?

That's a good idea also. My concern however is if someone zooms into the "dynamic" plot via the cookbook, it won't actually re-render anything.

**Comment by jukent** [comment]
This is looking really strong! Everything I noticed is already captured by @philipc2 's comments

**Comment by erogluorhan** [comment]
> "dynamic" option not actually being dynamic in the rendered notebook

Oops, with this comment, I just got what you meant with that warning about dynamic plots in rendered notebooks earlier today. Okay, I will put a warning about this

**Comment by erogluorhan** [comment]
I believe I have addressed all thelatest things suggested. Namely:

> Only thing that appears to be missing is a note/warning regarding the "dynamic" option not actually being dynamic in the rendered notebook.

> Need to still add the "Interactive" section to the "Structure" section of the README.

> For the "Hover" section, can you modify the clim to center the colorbar about 0? clim=(-4e-4, 4e-4) should do the trick

**Comment by philipc2** [comment]
> I believe I have addressed all thelatest things suggested. Namely:
> 
> > Only thing that appears to be missing is a note/warning regarding the "dynamic" option not actually being dynamic in the rendered notebook.
> 
> > Need to still add the "Interactive" section to the "Structure" section of the README.
> 
> > For the "Hover" section, can you modify the clim to center the colorbar about 0? clim=(-4e-4, 4e-4) should do the trick

These additions are perfect!

**Review by philipc2 — CHANGES_REQUESTED** [review]
Almost there! A few more minor suggestions
* Refer to Holoviz as HoloViz for consistency throughout 
* The title "HoloViz Tools" could be rephrased, I'm not a big fan of using the word "Tools", maybe "HoloViz Packages" (Technically, the only HoloViz package used in this notebook is HoloViews, so we should maybe reconsider the use of HoloViz throughout).  Any thoughts?

**Comment by erogluorhan** [comment]
> Almost there! A few more minor suggestions
> 
> * Refer to Holoviz as HoloViz for consistency throughout
> * The title "HoloViz Tools" could be rephrased, I'm not a big fan of using the word "Tools", maybe "HoloViz Packages" (Technically, the only HoloViz package used in this notebook is HoloViews, so we should maybe reconsider the use of HoloViz throughout).  Any thoughts?

> * Refer to Holoviz as HoloViz for consistency throughout

Done

> * The title "HoloViz Tools" could be rephrased, I'm not a big fan of using the word "Tools", maybe "HoloViz Packages" (Technically, the only HoloViz package used in this notebook is HoloViews, so we should maybe reconsider the use of HoloViz throughout).  Any thoughts?

HoloViz Plots, HoloViz Functions, or HoloViz Functionality? I lean towards HoloViz Plots. I think HoloViz Packages would also work as we are using geoviews, datashader through holoviews.opereations despite not directly for interactivity.

Originally I wanted to use "HoloViz Visualizations" but it sounded duplicative right under the chapter name "Interactive Visualization ...".

**Comment by erogluorhan** [comment]
Hey @philipc2 I have pushed the renaming of chapter and the notebook as we discussed, so this should good for another review

**Review by philipc2 — APPROVED** [review]
Looks great! Gave it a final read through and all looks good.

**Pull request merged**
