### PR TITLE
Change BinderHub

### PR DESCRIPTION
**Pull request by kafitzgerald**
Giving this a try to see if we can get things working.

### CODE REVIEW

**Review by jukent — APPROVED** [review]
Thanks let's hope 2i2c works. @brian-rose and @ktyle can you confirm if this is all we need to do to make the change?

**Review by ktyle — APPROVED** [review]
This runs fine on the 2i2c Binder so I think it's good to go for now!

**Comment by brian-rose** [comment]
With this change, the "launch" buttons on individual chapter pages now point to the 2i2c binder. The binder badge on the README page still points to the Pythia binder. That badge is manually configured in the README file [here](https://github.com/ProjectPythia/advanced-viz-cookbook/blob/9253520b1831ff0920a6bdfe7e93096a0c81123d/README.md?plain=1#L5)

**Comment by kafitzgerald** [comment]
> With this change, the "launch" buttons on individual chapter pages now point to the 2i2c binder. The binder badge on the README page still points to the Pythia binder. That badge is manually configured in the README file [here](https://github.com/ProjectPythia/advanced-viz-cookbook/blob/9253520b1831ff0920a6bdfe7e93096a0c81123d/README.md?plain=1#L5)

Thanks for noting this!  I was waiting to hear from Julia on what hub we should move to before making that update (clearly I should've done a quick search before putting in this PR - whoops).  Interestingly, it seems like they are both working now.

**Comment by jukent** [comment]
@brian-rose I was wondering about that, and went to fix it - but while I started the edits, the Binder resolved. Clicking the badge from the README, any of the pages, or from the cookbook gallery all load fairly quickly now.

**Comment by jukent** [comment]
Might need to re-publish the Cookbooks gallery for that binder link to point to 2i2c as well.

**Comment by brian-rose** [comment]
Both binders *should* work! And you can always launch the cookbook (any cookbook) in either binder manually by visiting either https://binder.projectpythia.org or https://hub.binder.pythia.2i2c.cloud/ and pasting in the repo name. The links in the cookbook are mostly just for convenience so users can click to deploy and not have to think about or care which binder there are visiting.

So having different binder links in the README versus the individual chapter pages isn't really a problem, as long as both binders are functional.

I believe the Pythia gallery pulls the binder link from the README file, not the config file. But I don't remember exactly.

In an ideal world there would be only one binder link per cookbook to maintain... That might be something to explore as part of the MySTification of the cookbook template.

**Comment by brian-rose** [comment]
Yes, it seems like sometimes a bad image gets created on the binder. A simple workaround is often just to push a trivial new commit to the main branch of the cookbook repo, which then forces the binder to rebuild a new image for that repo. That seems to have resolved the problem in this case.

**Pull request merged**
